# Generated by Django 6.0.7 on 2026-07-08 07:57

import analyzer.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_file', models.FileField(upload_to=analyzer.models.resume_upload_path)),
                ('original_filename', models.CharField(max_length=255)),
                ('job_description', models.TextField(blank=True, null=True)),
                ('extracted_text', models.TextField(blank=True)),
                ('ats_score', models.FloatField(default=0)),
                ('ats_grade', models.CharField(blank=True, max_length=50)),
                ('jd_match_percent', models.FloatField(blank=True, null=True)),
                ('report_json', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Resume Analyses',
                'ordering': ['-created_at'],
            },
        ),
    ]
